# Generated by Django 6.0.2 on 2026-02-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='SocialLink',
            new_name='Social',
        ),
    ]
