# Generated by Django 6.0.2 on 2026-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0002_rename_contactinfo_contact_rename_sociallink_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='logo_img',
        ),
        migrations.AddField(
            model_name='social',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
